[project]
name = "python-litestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litestar[standard,standart]>=2.16.0",
]
